name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run ruff
        run: |
          ruff check --output-format=github
      - name: Run bandit
        run: |
          pip3 install bandit
          bandit .
          if [[ $? -eq 0 ]]; then
            echo "No security issues found"
          else
            echo "Security issues found"
            exit 1
          fi
      - name: Run tests and collect coverage
        run: |
          pytest --verbose --cov .
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: unittests
          verbose: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
